#!/bin/sh
set -e

# ---------------------------------------------------------------------------
# Bootstrap BIOAF_ENCRYPTION_KEYS if missing.
#
# Background: v0.13.0 introduced at-rest column encryption gated on the
# BIOAF_ENCRYPTION_KEYS env var. On a fresh install or a v0.13.x->v0.13.y
# upgrade, the host-side ./install.sh ensure-encryption-key step seeds the
# key into docker/.env before the backend container starts. But for
# upgrades FROM any version < 0.13.0, the running bioaf script's
# cmd_update was parsed into memory before the git checkout brought in
# v0.13.0's version, so the ensure-encryption-key step never executes.
# The backend container would then refuse to start, breaking the upgrade
# for non-technical operators (no SSH-in remediation is acceptable).
#
# The fix has to live in something that IS read fresh from disk during
# that upgrade. docker-compose.yml is re-read on every `$DC up -d`, and
# the backend image is re-pulled. So the v0.13.1 docker-compose.yml
# mounts the host's docker/.env at /host/.env (writable), and this
# entrypoint writes the new key to that mount so subsequent compose
# invocations pass it through as the env var.
#
# Skipped (no-op) when:
#   - BIOAF_ENCRYPTION_KEYS is already set (fresh installs, normal upgrades,
#     Kubernetes deployments where the Secret provides the value).
#   - /host/.env is not present (Kubernetes path; the Secret handles it).
#
# Fails loudly when:
#   - The variable is empty AND /host/.env is present but not writable
#     (the upgrade would be silently incomplete otherwise; better to fail).
# ---------------------------------------------------------------------------

bootstrap_encryption_key() {
    if [ -n "${BIOAF_ENCRYPTION_KEYS:-}" ]; then
        return 0
    fi

    if [ ! -e /host/.env ]; then
        # No host env file mounted: this is the Kubernetes (Helm) path where
        # the Secret should already have supplied BIOAF_ENCRYPTION_KEYS. If
        # we get here, the operator misconfigured the chart. Fail clearly.
        echo "FATAL: BIOAF_ENCRYPTION_KEYS is unset and no host .env is mounted." >&2
        echo "  On Kubernetes, ensure the chart's encryption Secret exists." >&2
        echo "  See decisions/ADR-047-data-at-rest-encryption.md." >&2
        return 1
    fi

    if [ ! -w /host/.env ]; then
        echo "FATAL: BIOAF_ENCRYPTION_KEYS is unset and /host/.env is read-only." >&2
        echo "  The container cannot auto-generate a persistent key. This will" >&2
        echo "  break the upgrade. Make docker/.env writable by the container" >&2
        echo "  user, or set BIOAF_ENCRYPTION_KEYS yourself, then restart." >&2
        return 1
    fi

    # Idempotency guard: if .env already has a non-empty BIOAF_ENCRYPTION_KEYS
    # line, the env var should have been populated by compose. If it wasn't,
    # something went wrong with env-file expansion. Refuse to overwrite a
    # value that might be encrypting existing data.
    existing_line=$(grep -E "^BIOAF_ENCRYPTION_KEYS=" /host/.env 2>/dev/null | tail -1 || true)
    existing_value=${existing_line#BIOAF_ENCRYPTION_KEYS=}
    if [ -n "$existing_value" ]; then
        echo "WARNING: BIOAF_ENCRYPTION_KEYS env var is empty but /host/.env has a value." >&2
        echo "  Refusing to overwrite. Investigate the env-file plumbing." >&2
        export BIOAF_ENCRYPTION_KEYS="$existing_value"
        return 0
    fi

    # Generate a Fernet key inside the container. python3 + cryptography are
    # already in this image (cryptography is a hard requirement of the
    # backend), so no additional dependency is introduced.
    new_key=$(python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())")
    if [ -z "$new_key" ] || [ "${#new_key}" -ne 44 ]; then
        echo "FATAL: Failed to generate a Fernet key inside the container." >&2
        return 1
    fi

    # Append rather than sed-in-place: bind-mounted single files lose their
    # inode binding under atomic-rename writes, so the container's view of
    # /host/.env would orphan. compose's env-file parser uses last-occurrence-
    # wins for duplicate keys, so appending is safe even if a blank
    # BIOAF_ENCRYPTION_KEYS= line happens to exist further up the file.
    {
        printf '\n'
        printf '# Auto-generated by the backend container on %s.\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
        printf '# This typically only happens on upgrades from < 0.13.0 where the\n'
        printf '# host-side ensure-encryption-key step could not run.\n'
        printf '# LOSING THIS VALUE LOSES THE DATA -- back it up alongside the DB dump.\n'
        printf 'BIOAF_ENCRYPTION_KEYS=%s\n' "$new_key"
    } >> /host/.env

    echo "INFO: BIOAF_ENCRYPTION_KEYS was missing; auto-generated a new Fernet key"
    echo "INFO: and persisted it to docker/.env on the host. Future container"
    echo "INFO: restarts will pick it up via compose env-file expansion."
    echo "INFO: Operator action: back up this key value separately from the DB dump."

    export BIOAF_ENCRYPTION_KEYS="$new_key"
}

bootstrap_encryption_key

# Run migrations if requested (non-fatal -- container starts regardless)
if [ "${RUN_MIGRATIONS:-false}" = "true" ]; then
    echo "Running database migrations..."
    if alembic -c alembic/alembic.ini upgrade head; then
        echo "Migrations completed successfully."
    else
        echo "WARNING: Migrations failed. The application will start without migrations."
        echo "Run 'alembic -c alembic/alembic.ini upgrade head' manually to retry."
    fi
fi

exec "$@"
