"""A file is a catalogued asset, so it carries an identity of its own.

Projects, experiments and samples have carried a `uuid` since migration 080.
`File` did not, and it is the one bioAF most needs: a file is the thing that gets
exported, published and pointed at from a pipeline run, and the only identity it
had was a row id and a storage path.

**A path is never an identity.** Measured on the live system: reassigning a file
between experiments physically moves the object and rewrites the row, so the
integer id survives and the `storage_uri` CHANGES. Anything that recorded the
path recorded something mutable, and two places in bioAF do exactly that.

The owner's framing decides the rest: "It's an ISBN. I didn't write the book, but
need to catalog it for later recall." So the identifier is assigned on ingest
whatever the provenance (uploaded, generated by a pipeline, pulled from a public
archive), and it is never reissued.

This is the substrate only. Nothing emits a UID into a samplesheet yet, because
that also requires the layer that maps every identifier back to
PROJECT | EXPERIMENT | SAMPLE | FILE on every human-readable surface; shipping the
emission without the mapping would push opaque identifiers at scientists, which
design 05 section 3 forbids.
"""

import uuid as uuid_pkg

import pytest
from sqlalchemy import select, text
from sqlalchemy.exc import IntegrityError

from app.models.file import File
from app.services.file_service import FileService


async def _file(session, admin_user, filename="a.fastq.gz") -> File:
    return await FileService.create_file_record(
        session,
        org_id=admin_user.organization_id,
        user_id=admin_user.id,
        filename=filename,
        storage_uri=f"gs://bucket/{filename}",
        size_bytes=None,
        md5_checksum=None,
        file_type="fastq",
    )


@pytest.mark.asyncio
async def test_a_new_file_is_catalogued_on_creation(session, admin_user):
    """Assigned on ingest, regardless of provenance. The identifier says "bioAF
    is tracking this", not "bioAF made this"."""
    f = await _file(session, admin_user)

    assert isinstance(f.uuid, uuid_pkg.UUID)


@pytest.mark.asyncio
async def test_a_pipeline_output_is_catalogued_too(session, admin_user):
    """The ISBN framing settles this: bioAF did not write the book either way."""
    f = await FileService.create_file_record(
        session,
        org_id=admin_user.organization_id,
        user_id=None,
        filename="out.bam",
        storage_uri="gs://bucket/out.bam",
        size_bytes=None,
        md5_checksum=None,
        file_type="bam",
        source_type="pipeline_output",
    )

    assert isinstance(f.uuid, uuid_pkg.UUID)


@pytest.mark.asyncio
async def test_two_files_never_share_an_identity(session, admin_user):
    a = await _file(session, admin_user, "a.fastq.gz")
    b = await _file(session, admin_user, "b.fastq.gz")

    assert a.uuid != b.uuid


@pytest.mark.asyncio
async def test_the_database_refuses_a_duplicate_identity(session, admin_user):
    """Uniqueness is enforced by the database, not by the application. A
    catalogue number that two rows can share is not a catalogue number."""
    a = await _file(session, admin_user, "a.fastq.gz")
    b = await _file(session, admin_user, "b.fastq.gz")

    with pytest.raises(IntegrityError):
        await session.execute(text("UPDATE files SET uuid = :u WHERE id = :i"), {"u": str(a.uuid), "i": b.id})
        await session.flush()


@pytest.mark.asyncio
async def test_the_integer_id_is_still_the_key_the_system_joins_on(session, admin_user):
    """Add alongside, never replace. The integer is a storage detail that never
    leaves the system; the UUID is the contract with the outside world and is
    never used for joins."""
    f = await _file(session, admin_user)

    assert isinstance(f.id, int)
    assert f.uuid != f.id


@pytest.mark.asyncio
async def test_identity_survives_the_file_moving(session, admin_user):
    """The reason a path cannot be the identity. Reassignment rewrites
    storage_uri in place, so anything keyed on the path has been invalidated
    while the asset itself has not changed at all."""
    f = await _file(session, admin_user)
    original = f.uuid

    f.storage_uri = "gs://other-bucket/experiments/9/a.fastq.gz"
    await session.flush()
    await session.refresh(f)

    assert f.uuid == original


@pytest.mark.asyncio
async def test_every_file_in_the_table_is_catalogued(session, admin_user):
    """No row may exist without an identity, including rows written by paths
    that do not go through create_file_record."""
    await session.execute(
        text(
            "INSERT INTO files (organization_id, gcs_uri, storage_uri, filename, file_type, tags_json, source_type) "
            "VALUES (:o, :u, :u, 'direct.bam', 'bam', '[]'::jsonb, 'upload')"
        ),
        {"o": admin_user.organization_id, "u": "gs://bucket/direct.bam"},
    )
    await session.flush()

    uncatalogued = (await session.execute(select(File).where(File.uuid.is_(None)))).scalars().all()

    assert uncatalogued == []
