// Literature feature API client and types.
//
// Generated by hand to mirror backend/app/api/literature.py. Keeping it in a
// dedicated module so the existing api.ts surface stays focused.

import { api } from "./api";
import { getToken } from "./auth";

const API_URL = process.env.NEXT_PUBLIC_API_URL || "";

export type Provenance = "user_upload" | "source_search" | "lit_review_run";
export type ScopeType = "global" | "project" | "experiment";
export type LiteratureSourceName =
  | "pubmed"
  | "biorxiv"
  | "europepmc"
  | "semanticscholar";
export type ReadingStatusValue = "unread" | "reading" | "read";
export type SearchStatus =
  | "queued"
  | "running"
  | "complete"
  | "partial"
  | "failed";
export type RecommendationStatus = "pending" | "accepted" | "dismissed";
export type RelevanceBucket = "high" | "medium" | "low";

export interface Author {
  given?: string | null;
  family?: string | null;
  orcid?: string | null;
}

export interface Association {
  id: number;
  scope_type: ScopeType;
  scope_id: number | null;
  scope_name: string | null;
  parent_project_id: number | null;
  parent_project_name: string | null;
  added_by_user_id: number;
  added_at: string;
}

export interface Paper {
  id: number;
  title: string;
  authors: Author[];
  publication_date: string | null;
  journal: string | null;
  doi: string | null;
  pmid: string | null;
  abstract: string | null;
  provenance: Provenance;
  source: string | null;
  added_by_user_id: number | null;
  has_pdf: boolean;
  has_full_text: boolean;
  extraction_status: string;
  extraction_error: string | null;
  comment_count: number;
  reading_status: ReadingStatusValue | null;
  dismissed: boolean;
  in_library: boolean;
  associations: Association[];
  created_at: string;
  updated_at: string;
}

export interface RecommendationNote {
  review_run_id: number;
  experiment_id: number;
  experiment_name: string | null;
  project_name: string | null;
  relevance_score: number;
  relevance_bucket: RelevanceBucket;
  reasoning: string | null;
  llm_provider: string;
  llm_model: string;
  created_at: string;
}

export interface PaperListResponse {
  items: Paper[];
  total: number;
  page: number;
  page_size: number;
}

export interface Comment {
  id: number;
  paper_id: number;
  user_id: number;
  user_name: string | null;
  parent_id: number | null;
  body: string | null;
  deleted: boolean;
  deleted_by_user_id: number | null;
  created_at: string;
  updated_at: string;
}

export interface SourceConfig {
  source: LiteratureSourceName;
  enabled: boolean;
  has_api_key: boolean;
  rate_limit_override: number | null;
  last_success_at: string | null;
  last_status: string | null;
}

export interface SearchSummary {
  id: number;
  query_text: string;
  sources: LiteratureSourceName[];
  per_source_status: Record<string, string>;
  status: SearchStatus;
  result_count: number | null;
  error_message: string | null;
  started_at: string | null;
  completed_at: string | null;
  created_at: string;
}

export interface LitReviewRun {
  id: number;
  experiment_id: number;
  triggered_by_user_id: number;
  status: SearchStatus;
  llm_provider: string;
  llm_model: string;
  expansion_queries_json: string[] | null;
  candidate_count: number | null;
  recommendation_count: number | null;
  max_recommendations: number;
  score_threshold: number;
  started_at: string | null;
  completed_at: string | null;
  error_message: string | null;
  created_at: string;
}

export interface Recommendation {
  id: number;
  paper: Paper;
  experiment_id: number;
  review_run_id: number;
  relevance_score: number;
  relevance_bucket: RelevanceBucket;
  reasoning: string | null;
  status: RecommendationStatus;
  decided_by_user_id: number | null;
  decided_at: string | null;
  created_at: string;
}

export interface LiteratureConfig {
  scope_type: string;
  scope_id: number | null;
  abstracts_enabled: boolean;
  comments_enabled: boolean;
  full_text_enabled: boolean;
  max_tokens: number;
}

export interface PaperFilters {
  scope_type?: ScopeType;
  scope_id?: number;
  project_id?: number;
  experiment_id?: number;
  provenance?: Provenance;
  added_by_user_id?: number;
  has_full_text?: boolean;
  source?: string;
  year_min?: number;
  year_max?: number;
  in_library?: boolean | null;
  include_active?: boolean;
  include_dismissed?: boolean;
  reading_status?: ReadingStatusValue[];
  sort?: "title" | "year" | "added" | "comments";
  page?: number;
  page_size?: number;
}

function buildQuery(params: PaperFilters | Record<string, unknown>): string {
  const entries: string[] = [];
  for (const [k, v] of Object.entries(params)) {
    if (v === undefined || v === null || v === "") continue;
    if (Array.isArray(v)) {
      for (const item of v) {
        if (item === undefined || item === null || item === "") continue;
        entries.push(`${encodeURIComponent(k)}=${encodeURIComponent(String(item))}`);
      }
      continue;
    }
    entries.push(`${encodeURIComponent(k)}=${encodeURIComponent(String(v))}`);
  }
  return entries.length ? `?${entries.join("&")}` : "";
}

export const literature = {
  listPapers: (filters: PaperFilters = {}) =>
    api.get<PaperListResponse>(`/api/literature/papers${buildQuery(filters)}`),
  getPaper: (id: number) => api.get<Paper>(`/api/literature/papers/${id}`),
  createPaper: (body: {
    title: string;
    authors: Author[];
    doi?: string;
    pmid?: string;
    journal?: string;
    publication_date?: string;
    abstract?: string;
    associations?: { scope_type: ScopeType; scope_id?: number | null }[];
  }) => api.post<Paper>("/api/literature/papers", body),
  updatePaper: (id: number, body: Partial<Paper>) =>
    api.patch<Paper>(`/api/literature/papers/${id}`, body),
  deletePaper: (id: number) => api.delete<void>(`/api/literature/papers/${id}`),
  uploadPaper: (file: File, extra?: Record<string, string>) =>
    api.upload<Paper>("/api/literature/papers/upload", file, extra),
  reExtract: (id: number) =>
    api.post<Paper>(`/api/literature/papers/${id}/extract`),
  dismissPaper: (id: number, reason?: string) =>
    api.post<unknown>(`/api/literature/papers/${id}/dismiss`, { reason }),
  reverseDismiss: (id: number) =>
    api.post<unknown>(`/api/literature/papers/${id}/dismiss/reverse`),
  addToLibrary: (id: number) =>
    api.post<Paper>(`/api/literature/papers/${id}/add-to-library`),
  bulkAddToLibrary: (paper_ids: number[]) =>
    api.post<{ added: number[]; not_found: number[] }>(
      "/api/literature/papers/bulk-add-to-library",
      { paper_ids },
    ),
  recommendationNotes: (id: number) =>
    api.get<RecommendationNote[]>(
      `/api/literature/papers/${id}/recommendation-notes`,
    ),

  listAssociations: (paperId: number) =>
    api.get<Association[]>(`/api/literature/papers/${paperId}/associations`),
  addAssociation: (paperId: number, body: { scope_type: ScopeType; scope_id?: number | null }) =>
    api.post<Association>(`/api/literature/papers/${paperId}/associations`, body),
  deleteAssociation: (paperId: number, associationId: number) =>
    api.delete<void>(`/api/literature/papers/${paperId}/associations/${associationId}`),

  listComments: (paperId: number) =>
    api.get<{ items: Comment[] }>(`/api/literature/papers/${paperId}/comments`),
  addComment: (paperId: number, body: { body: string; parent_id?: number | null }) =>
    api.post<Comment>(`/api/literature/papers/${paperId}/comments`, body),
  updateComment: (commentId: number, body: { body: string }) =>
    api.patch<Comment>(`/api/literature/comments/${commentId}`, body),
  deleteComment: (commentId: number) =>
    api.delete<void>(`/api/literature/comments/${commentId}`),

  getReadingStatus: (paperId: number) =>
    api.get<{ paper_id: number; user_id: number; status: ReadingStatusValue }>(
      `/api/literature/papers/${paperId}/reading-status`,
    ),
  setReadingStatus: (paperId: number, status: ReadingStatusValue) =>
    api.put<{ status: ReadingStatusValue }>(`/api/literature/papers/${paperId}/reading-status`, {
      status,
    }),

  citation: (paperId: number, format: "bibtex" | "ris" = "bibtex") =>
    fetch(`${API_URL}/api/literature/papers/${paperId}/citation?format=${format}`, {
      headers: {
        Authorization: `Bearer ${getToken() ?? ""}`,
      },
    }).then((r) => r.text()),

  listSources: () =>
    api.get<{ items: SourceConfig[] }>("/api/literature/sources"),
  updateSource: (
    source: LiteratureSourceName,
    body: { enabled?: boolean; api_key?: string; rate_limit_override?: number | null },
  ) => api.patch<SourceConfig>(`/api/literature/sources/${source}`, body),
  testSource: (source: LiteratureSourceName) =>
    api.post<{ success: boolean; message: string; latency_ms: number }>(
      `/api/literature/sources/${source}/test`,
    ),

  submitSearch: (body: {
    query: string;
    sources?: LiteratureSourceName[];
    max_per_source?: number;
  }) => api.post<SearchSummary>("/api/literature/searches", body),
  listSearches: () =>
    api.get<{ items: SearchSummary[]; total: number }>("/api/literature/searches"),
  getSearch: (id: number) =>
    api.get<SearchSummary>(`/api/literature/searches/${id}`),
  getSearchResults: (id: number) =>
    api.get<PaperListResponse>(`/api/literature/searches/${id}/results`),

  runLitReview: (experimentId: number, body?: {
    max_recommendations?: number;
    score_threshold?: number;
  }) =>
    api.post<LitReviewRun>(
      `/api/literature/experiments/${experimentId}/lit-review-runs`,
      body ?? {},
    ),
  listRuns: (experimentId: number) =>
    api.get<{ items: LitReviewRun[] }>(
      `/api/literature/experiments/${experimentId}/lit-review-runs`,
    ),
  getRun: (id: number) => api.get<LitReviewRun>(`/api/literature/lit-review-runs/${id}`),

  listRecommendations: (params: {
    experiment_id?: number;
    status?: RecommendationStatus;
  } = {}) =>
    api.get<{ items: Recommendation[]; total: number }>(
      `/api/literature/recommendations${buildQuery(params)}`,
    ),
  acceptRecommendation: (id: number) =>
    api.post<Recommendation>(`/api/literature/recommendations/${id}/accept`),
  dismissRecommendation: (id: number) =>
    api.post<Recommendation>(`/api/literature/recommendations/${id}/dismiss`),

  getOrgConfig: () => api.get<LiteratureConfig>("/api/literature/agent-review-config"),
  updateOrgConfig: (body: Partial<LiteratureConfig>) =>
    api.put<LiteratureConfig>("/api/literature/agent-review-config", body),

  getLitReviewSettings: () =>
    api.get<{ relevance_threshold: number }>("/api/literature/settings/lit-review"),
  updateLitReviewSettings: (relevance_threshold: number) =>
    api.put<{ relevance_threshold: number }>(
      "/api/literature/settings/lit-review",
      { relevance_threshold },
    ),
};

export function formatAuthors(authors: Author[]): string {
  if (!authors || authors.length === 0) return "";
  if (authors.length >= 3) {
    const first = authors[0];
    return `${first.family ?? ""}, ${first.given ?? ""} et al.`.trim();
  }
  return authors
    .map((a) => `${a.family ?? ""}, ${a.given ?? ""}`.trim().replace(/^,\s*/, ""))
    .join("; ");
}

export function formatYear(date: string | null): string {
  if (!date) return "";
  return date.slice(0, 4);
}

// Render an association as a single-line breadcrumb:
//   project:    "Atlas of TGF-beta"
//   experiment with parent project: "Atlas of TGF-beta > Exp One"
//   experiment without parent project: "Exp One"
//   global: "Global"
export function formatAssociation(a: Association): string {
  if (a.scope_type === "global" || a.scope_id === null) {
    return "Global";
  }
  if (a.scope_type === "project") {
    return a.scope_name ?? `Project #${a.scope_id}`;
  }
  const expLabel = a.scope_name ?? `Experiment #${a.scope_id}`;
  if (a.parent_project_name) {
    return `${a.parent_project_name} > ${expLabel}`;
  }
  return expLabel;
}

const _HTML_ENTITIES: Record<string, string> = {
  amp: "&",
  lt: "<",
  gt: ">",
  quot: '"',
  apos: "'",
  nbsp: " ",
};

// Defensive fallback for any rows that were stored before the backend
// adapters started stripping HTML on ingestion. Decodes named/numeric
// entities and strips inline tags. New records arrive clean from the
// backend; this is a one-time bridge.
export function cleanText(value: string | null | undefined): string {
  if (!value) return "";
  const decoded = value.replace(/&(#x?[0-9a-fA-F]+|[a-zA-Z]+);/g, (m, body) => {
    if (body.startsWith("#x") || body.startsWith("#X")) {
      const cp = parseInt(body.slice(2), 16);
      return Number.isFinite(cp) ? String.fromCodePoint(cp) : m;
    }
    if (body.startsWith("#")) {
      const cp = parseInt(body.slice(1), 10);
      return Number.isFinite(cp) ? String.fromCodePoint(cp) : m;
    }
    return _HTML_ENTITIES[body] ?? m;
  });
  return decoded.replace(/<[^>]+>/g, "").replace(/\s+/g, " ").trim();
}
